
service: bmi

plugins:
  - serverless-offline


provider:
  name: aws
  runtime: nodejs12.x


functions:
  bmiCalculate:
    handler: handler.bmiCalculate
    events:
      - http:
         cors: true
         path: bmi
         method: post
